### ISSUE TITLE
No License File

### ISSUE THREAD

**Issue by r-southworth** [natemoo-re/astro-remote#10]
Could you add a license file? I am hoping for something permissive open source but I can't use this at all without knowing some kind of license.

**Comment by r-southworth** [comment]
@natemoo-re Any chance of adding a license file for this?

**Comment by natemoo-re** [comment]
Closed in [db73272](https://github.com/natemoo-re/astro-remote/commit/db7327227470c3df16bcee1cf8eaae3f35a6e570)
