### ISSUE TITLE
Throws error when building.

### ISSUE THREAD

**Issue by JojokCreator** [natemoo-re/astro-remote#17]
I'm guessing the latest pull request may fix this. Getting this when building.

```
Error: Invalid second argument for `transform`! Expected `Transformer[]` but got `object`
--
15:26:55.883 | at B (file:///vercel/path0/node_modules/ultrahtml/dist/index.js:1:4646)
15:26:55.883 | at markdown (file:///vercel/path0/dist/chunks/prerender_x7JghXdG.mjs:3260:10)
15:26:55.883 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
15:26:55.883 | at async file:///vercel/path0/dist/chunks/prerender_x7JghXdG.mjs:3281:19
```

**Comment by Adammatthiesen** [comment]
Hi, i'm guessing your trying to contribute?  if so yes!  we are working on fixing some of the code to be able to upgrade all the deps as some of them change the way their code works.

On another note, if you are wanting to build based on the `main` branch you can use `pnpm install --frozen-lockfile` and it will install the proper versions to get it to work
