### ISSUE TITLE
Trailing spaces causes initial characters to be swallowed

### ISSUE THREAD

**Issue by delucis** [natemoo-re/astro-remote#27]
If the `content` string passed to `<Markdown>` ends in one or more spaces, the equivalent number of characters are removed from the start of the content.

Some examples:

|   | Input | Output |
|---|--------|--------|
| ✅ | `<mark>Highlighted word</mark> with no trailing space` | `<mark>Highlighted word</mark> with no trailing space` |
| ❌ | `<mark>Highlighted word</mark> with trailing space ` | `mark>Highlighted word</mark> with trailing space` |
| ❌ | `Non-initial <mark>Highlighted word</mark> with trailing spaces   ` | `-initial <mark>Highlighted word</mark> with trailing spaces` | 

Minimal reproduction: https://stackblitz.com/edit/github-futqf6?file=src%2Fpages%2Findex.astro

I wasn’t able to reproduce this in the [`marked` playground](https://marked.js.org/demo/), so I’m guessing it’s something specific happening here or perhaps in the plugins `astro-remote` uses?

**Comment by Adammatthiesen** [comment]
darn... I thought we had this issue fixed... its something with the [dedent function](https://github.com/natemoo-re/astro-remote/blob/c29a49bf672c2f5f1209fbf6e6dd5a52366b4632/packages/astro-remote/lib/utils.ts#L46) that seems to be causing it...  I guess we only partially fixed it in #23 😢
