### ISSUE TITLE
Adding spaces at specific places removes first characters.

### ISSUE THREAD

**Issue by minht11** [natemoo-re/astro-remote#7]
Having spaces and newlines or spaces at the end of the paragraph makes it so first characters are not rendered correctly. Given code like this:
```astro
---
import { Markdown } from "astro-remote";

// Working as expected
const c0 = `Most .`;

// 1 space
const c1 = `Most 
.`;

// 2 spaces
const c2 = `Most  
.`;

// Space at the end
const c3 = `Most . `;

const content = [c0, c1, c2, c3];
---
<div>
	{content.map((c) => <Markdown san>{c}</Markdown>)}
</div>
```
Result is
<img width="89" alt="image" src="https://user-images.githubusercontent.com/8914032/214810366-e5c053e9-f0c5-4182-8f59-462d7c912e7b.png">

[Reproduction](https://codesandbox.io/p/sandbox/cocky-breeze-4r5txo?file=%2Fsrc%2Fpages%2Findex.astro&selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A19%2C%22startLineNumber%22%3A13%7D%5D)

This is not issue with marked since it handles those use [cases correctly](https://marked.js.org/demo/?outputType=html&text=Most%20%0A.&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.2.12)

**Comment by Adammatthiesen** [comment]
> Having spaces and newlines or spaces at the end of the paragraph makes it so first characters are not rendered correctly. Given code like this:
> 
> ```astro
> ---
> import { Markdown } from "astro-remote";
> 
> // Working as expected
> const c0 = `Most .`;
> 
> // 1 space
> const c1 = `Most 
> .`;
> 
> // 2 spaces
> const c2 = `Most  
> .`;
> 
> // Space at the end
> const c3 = `Most . `;
> 
> const content = [c0, c1, c2, c3];
> ---
> <div>
> 	{content.map((c) => <Markdown san>{c}</Markdown>)}
> </div>
> ```
> 
> Result is <img alt="image" width="89" src="https://user-images.githubusercontent.com/8914032/214810366-e5c053e9-f0c5-4182-8f59-462d7c912e7b.png">
> 
> [Reproduction](https://codesandbox.io/p/sandbox/cocky-breeze-4r5txo?file=%2Fsrc%2Fpages%2Findex.astro&selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A19%2C%22startLineNumber%22%3A13%7D%5D)
> 
> This is not issue with marked since it handles those use [cases correctly](https://marked.js.org/demo/?outputType=html&text=Most%20%0A.&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.2.12)

So the new PR about to be opened from the branch `testing-issue-#7` will include resolutions to some of the issues your facing.  

BUT this issue is not entirely related to `astro-remote`... aside from the small fix included above,  

To preserve the formatting of your strings when they're rendered as Markdown through astro-remote
![testissue7](https://github.com/natemoo-re/astro-remote/assets/30383579/df7f16e0-db8f-40d9-8625-32ecc939c85b)
, you might need to escape the trailing spaces and newlines. Here's how you could do that using the example from your Reproduction:

```astro
---
import { Markdown } from "astro-remote";

// Working as expected
const c0 = `Most .`;

// 1 space
const c1 = `Most \\
.`;

// 2 spaces
const c2 = `Most  \\
.`;

// Space at the end
const c3 = `Most . `;

const content = [c0, c1, c2, c3];
---
<div>
    {content.map((c) => <Markdown>{c}</Markdown>)}
</div>
```

The Above resolved the issues after I updated a internal function

**Comment by minht11** [comment]
Upgrading from 0.2.4 to 0.3.2 we got major performance issue in production, the only change was updating this dependency. It slowed the whole astro node instance, I don't see it in dev/preview mode/
